<<<<<<< HEAD:resume.Rmd
---
title: "Lindsey Dorson's Resume"
author: Lindsey Dorson
date: ""
output:
  pagedown::html_resume:
    css:
      - override.css
      - resume
    self_contained: false
knit: pagedown::chrome_print
---

# Aside

## Contact Info {#contact}

-   <i class="fa fa-envelope"></i> [lindsey.dorson\@gmail.com](mailto:lindsey.dorson@gmail.com){.email}
-   <i class="fa fa-linkedin"></i> [linkedin.com/in/lindsey-dorson](https://www.linkedin.com/in/lindsey-dorson)
-   <i class="fa fa-github"></i> [github.com/ldorson](https://github.com/ldorson)
-   <i class="fa fa-phone"></i> +1 678-673-7442

## Skills {#skills}

-   [Technical Skills:]{.underline} Regression Analysis, Data Mining, Data Visualization, Causal Inference, Decision & Optimization Analysis, Forecasting

-   [Tools & Softwares:]{.underline} R (3 years), Excel (4 years), Git , Slack, STATA

-   [Presentation:]{.underline} Microsoft Office, R Markdown ([[1] Synthetic Stock Returns](https://github.com/ldorson/Financial-Econometrics), [[2] Risk Analysis](https://github.com/ldorson/Risk-Analysis-Using-Econometric-Models), [[3] Synthetic Program Website](https://ldorson.github.io/ProgramEval_website/))

-   [Non-Technical Skills:]{.underline} Time & Task Management, Communication, Goal & Detail Oriented

## Honors & Awards {#honors}

-   Thomas Herndon Award (2021)
-   Michael Raper Honorary Economics Scholarship (2020)
-   Faye S. McIntyre Scholarship (2019)
-   Presidents List (2020)
-   Dean's List (2017-2020)

## Organizations {#organ}

-   University of West Georgia Honors College
-   Business Honor Society - BGS
-   Economics Honor Society - ODE

## Disclaimer {#disclaimer}

This resume was made with the R [**pagedown**](https://github.com/rstudio/pagedown).

# Main

## Lindsey Dorson {#title}

Recent Economic analytics graduate that is proficiently skilled in data analysis, data visualization, and predictive modeling utilizing different optimization and probability techniques. Has a passion for detecting patterns and causal relationships in data and generating dynamic reports to illustrate findings.

## Education {data-icon="graduation-cap" data-concise="true"}

### Georgia State University

M.A. in Economics, Analytics Track

Atlanta, Georgia

December 2022

GPA: 3.96

Thesis: Impact of ACA Medicaid Expansion on Health Care Access Across Age Groups ([Thesis Report](https://github.com/ldorson/Capstone-ACA/blob/2362825a6bee10058f9d777fcb5365aa65c3b081/GSU%20Capstone%20Report.pdf))

### University of West Georgia

B.S. in Economics, Minor in Finance

Carrollton, GA

December 2020

GPA: 3.96, *summa cum laude*

## Work Experience {data-icon="laptop"}

### Finance & Data Analytics Intern

Robinson Weeks Partners

Atlanta, GA

May 2022 - Present

-   Analyzed the performance of the partner's investment portfolios utilizing excel & R. Additionally, backtested different portfolio allocations to gauge efficiency during different economic periods.
-   Conducted historical performance analysis on industrial real estate funds. Trended key deal inputs and presented to upper management.
-   Compiled and cleaned broker comp data for the development team in each real estate market of interest.
-   Listened to the earnings calls of top industrial real estate suppliers and potential customers to understand investment opportunities. Also, assisted in the review of financials (ratio analysis) provided by potential tenants to assess their financial strength in the general underwriting process.

### Graduate Assistant

GSU, Office of Supplemental Instruction

Atlanta, GA

Fall 2021 - Fall 2022

-   Tasked with creating animated videos utilizing animation software PowToon to help students with Intro to Microeconomics concepts (Marginal Analysis, Elasticity,etc.).
-   Duties include script creation, audio recording, and video editing along with additional administrative tasks.

### Business Statistics II Supplemental Instructor

UWG, Center for Academic Success

Carrollton, GA

Fall 2020

-   Conducted weekly study sessions over Business Statistics II material (Linear Regression, Decision Analysis, Forecasting, etc.) that encouraged student engagement and understanding.
-   Regularly incorporated excel as a supplement to class material to promote student's exposure.
=======
---
title: "Lindsey Dorson's Resume"
author: Lindsey Dorson
date: ""
output:
  pagedown::html_resume:
    css:
      - override.css
      - resume
    self_contained: false
knit: pagedown::chrome_print
---

# Aside

## Contact Info {#contact}

-   <i class="fa fa-envelope"></i> [lindsey.dorson\@gmail.com](mailto:lindsey.dorson@gmail.com){.email}
-   <i class="fa fa-linkedin"></i> [linkedin.com/in/lindsey-dorson](https://www.linkedin.com/in/lindsey-dorson)
-   <i class="fa fa-github"></i> [github.com/ldorson](https://github.com/ldorson)
-   <i class="fa fa-phone"></i> +1 678-673-7442

## Skills {#skills}

-   [Technical Skills:]{.underline} Regression Analysis, Data Mining, Data Visualization, Causal Inference, Decision & Optimization Analysis, Forecasting

-   [Software Programs:]{.underline} R (3 years), Excel (4 years), & STATA (1 year)

-   [Presentation:]{.underline} Microsoft Office, R Markdown ([[1] Synthetic Stock Returns](https://github.com/ldorson/Financial-Econometrics), [[2] Risk Analysis](https://github.com/ldorson/Risk-Analysis-Using-Econometric-Models), [[3] Synthetic Program Website](https://ldorson.github.io/ProgramEval_website/))

-   [Non-Technical Skills:]{.underline} Time & Task Management, Communication, Goal & Detail Oriented

## Honors & Awards {#honors}

-   Thomas Herndon Award (2021)
-   Michael Raper Honorary Economics Scholarship (2020)
-   Faye S. McIntyre Scholarship (2019)
-   Presidents List (2020)
-   Dean's List (2017-2020)

## Organizations {#organ}

-   University of West Georgia Honors College
-   Business Honor Society - BGS
-   Economics Honor Society - ODE

## Disclaimer {#disclaimer}

This resume was made with the R [**pagedown**](https://github.com/rstudio/pagedown).

# Main

## Lindsey Dorson {#title}

Economic analytics graduate student that is proficiently skilled in data analysis, data visualization, and predictive modeling utilizing different optimization and probability techniques. Has a passion for detecting patterns and causal relationships in data and generating dynamic reports to illustrate findings.

## Education {data-icon="graduation-cap" data-concise="true"}

### Georgia State University

M.A. in Economics, Analytics Track

Atlanta, Georgia

December 2022

GPA: 3.96

Thesis: Impact of ACA Medicaid Expansion on Health Care Access Across Age Groups ([Thesis Report](https://github.com/ldorson/Capstone-ACA/blob/2362825a6bee10058f9d777fcb5365aa65c3b081/GSU%20Capstone%20Report.pdf))

### University of West Georgia

B.S. in Economics, Minor in Finance

Carrollton, GA

December 2020

GPA: 3.96, *summa cum laude*

## Work Experience {data-icon="laptop"}

### Finance & Data Analytics Intern

Robinson Weeks Partners

Atlanta, GA

May 2022 - Present

-   Analyzed the performance of the partner's investment portfolios utilizing excel & R. Additionally, backtested different portfolio allocations to gauge efficiency during different economic periods.
-   Conducted historical performance analysis on industrial real estate funds. Trended key deal inputs and presented to upper management.
-   Compiled and cleaned broker comp data for the development team in each real estate market of interest.
-   Listened to the earnings calls of top industrial real estate suppliers and potential customers to understand investment opportunities. Also, assisted in the review of financials (ratio analysis) provided by potential tenants to assess their financial strength in the general underwriting process.

### Graduate Assistant

GSU, Office of Supplemental Instruction

Atlanta, GA

Fall 2021 - Fall 2022

-   Tasked with creating animated videos utilizing animation software PowToon to help students with Intro to Microeconomics concepts (Marginal Analysis, Elasticity,etc.).
-   Duties include script creation, audio recording, and video editing along with additional administrative tasks.

### Business Statistics II Supplemental Instructor

UWG, Center for Academic Success

Carrollton, GA

Fall 2020

-   Conducted weekly study sessions over Business Statistics II material (Linear Regression, Decision Analysis, Forecasting, etc.) that encouraged student engagement and understanding.
-   Regularly incorporated excel as a supplement to class material to promote student's exposure.
>>>>>>> ceb2f4d0bfa357e1515150095a43623aa58d4653:resume.rmd
